import type { TopicProfile } from "./types";

export const defaultTopics: TopicProfile[] = [
  {
    slug: "spinal-cord-injury",
    name: "Spinal Cord Injury",
    description:
      "SCI repair, neurorehabilitation, axonal regeneration, neuromodulation, and translational recovery studies.",
    terms: [
      "spinal cord injury",
      "SCI",
      "spinal cord regeneration",
      "neurorehabilitation",
      "axonal regeneration",
      "neural repair",
      "epidural stimulation",
    ],
    meshTerms: [
      "Spinal Cord Injuries",
      "Neural Regeneration",
      "Rehabilitation",
      "Electric Stimulation Therapy",
    ],
    koreanTerms: [
      "척수손상",
      "척수 손상",
      "척수 재생",
      "신경재활",
      "축삭 재생",
      "경막외 전기자극",
    ],
    highImpactJournals: [
      "Nature",
      "Science",
      "Cell",
      "Nature Medicine",
      "Science Translational Medicine",
      "The Lancet Neurology",
      "JAMA Neurology",
      "Brain",
      "Annals of Neurology",
      "Neurology",
      "Journal of Neurotrauma",
      "Spinal Cord",
    ],
    usNewsTerms: [
      "spinal cord injury",
      "spinal cord stimulation",
      "paralysis recovery",
      "neurorehabilitation",
    ],
    krNewsTerms: ["척수손상", "척수 손상", "마비 회복", "신경재활"],
  },
  {
    slug: "sarcopenia",
    name: "Sarcopenia",
    description:
      "Age-related muscle loss, frailty, cachexia, skeletal muscle biology, diagnostics, and intervention trials.",
    terms: [
      "sarcopenia",
      "muscle wasting",
      "frailty",
      "skeletal muscle",
      "aging muscle",
      "myopenia",
      "muscle function",
    ],
    meshTerms: [
      "Sarcopenia",
      "Muscle, Skeletal",
      "Frailty",
      "Aging",
      "Muscular Atrophy",
    ],
    koreanTerms: [
      "근감소증",
      "근육 감소",
      "노쇠",
      "골격근",
      "노화 근육",
      "근위축",
    ],
    highImpactJournals: [
      "Nature Medicine",
      "The Lancet",
      "JAMA",
      "BMJ",
      "Age and Ageing",
      "Journal of Cachexia, Sarcopenia and Muscle",
      "The Journals of Gerontology Series A",
      "Cell Metabolism",
      "Nature Aging",
      "Medicine and Science in Sports and Exercise",
      "Clinical Nutrition",
    ],
    usNewsTerms: [
      "sarcopenia",
      "muscle loss",
      "frailty",
      "aging muscle",
      "healthy aging",
    ],
    krNewsTerms: ["근감소증", "근육 감소", "노쇠", "고령 근육", "건강 노화"],
  },
  {
    slug: "brain-computer-interface",
    name: "Brain-Computer Interface",
    description:
      "Invasive and non-invasive BCI, neuroprosthetics, neural decoding, implants, robotics, and rehabilitation interfaces.",
    terms: [
      "brain-computer interface",
      "BCI",
      "brain machine interface",
      "neural interface",
      "neuroprosthetics",
      "neural decoding",
      "brain implant",
    ],
    meshTerms: [
      "Brain-Computer Interfaces",
      "Neural Prostheses",
      "Robotics",
      "Electroencephalography",
    ],
    koreanTerms: [
      "뇌-컴퓨터 인터페이스",
      "뇌 컴퓨터 인터페이스",
      "BCI",
      "뇌기계 인터페이스",
      "신경 인터페이스",
      "신경보철",
    ],
    highImpactJournals: [
      "Nature",
      "Science",
      "Cell",
      "Nature Medicine",
      "Nature Neuroscience",
      "Nature Biomedical Engineering",
      "Science Robotics",
      "The Lancet Neurology",
      "JAMA Neurology",
      "Brain",
      "Journal of Neural Engineering",
      "IEEE Transactions on Neural Systems and Rehabilitation Engineering",
    ],
    usNewsTerms: [
      "brain-computer interface",
      "brain implant",
      "neural interface",
      "neuroprosthetics",
      "BCI",
    ],
    krNewsTerms: [
      "뇌-컴퓨터 인터페이스",
      "뇌 컴퓨터 인터페이스",
      "뇌 임플란트",
      "신경 인터페이스",
      "신경보철",
    ],
  },
];

export function getTopicName(slug: string) {
  return defaultTopics.find((topic) => topic.slug === slug)?.name ?? slug;
}
